services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    restart: always
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
    expose:
      - "${PORT}"
    ports:
      - "${BLUE_PORT}:${PORT}"
    healthcheck:
      test:   ["CMD-SHELL", "node -e \"process.exit(0)\""]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - app-network

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    restart: always
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
    expose:
      - "${PORT}"
    ports:
      - "${GREEN_PORT}:${PORT}"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"process.exit(0)\""]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app_blue
      - app_green
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.tmpl:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/entrypoint.sh:/docker-entrypoint.d/10-envsubst.sh:ro
      - ./nginx-logs:/var/log/nginx
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - BLUE_PORT=${BLUE_PORT}
      - GREEN_PORT=${GREEN_PORT}
      - RELEASE_ID_BLUE=${RELEASE_ID_BLUE}
      - RELEASE_ID_GREEN=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    networks:
      - app-network

  alert_watcher:
    image: python:3.11-slim
    container_name: alert_watcher
    restart: always
    depends_on:
      - nginx
    volumes:
      - ./nginx-logs:/var/log/nginx
      - ./watcher.py:/app/watcher.py
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    command: >
      sh -c "
      pip install -r requirements.txt &&
      echo 'Starting Alert Watcher now...' &&
      exec python3 /app/watcher.py
      "
    environment:
      - LOG_PATH=${LOG_PATH}
      - ERROR_LOG_PATH=${ERROR_LOG_PATH}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ACTIVE_POOL=${ACTIVE_POOL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD}
      - WINDOW_SIZE=${WINDOW_SIZE}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC}
    networks:
      - app-network

volumes:
  nginx-logs:

networks:
  app-network:
    driver: bridge
