version: "3.9"

services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - PORT=${BLUE_PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "${BLUE_PORT}:${BLUE_PORT}"
    healthcheck:
      test:   ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - app-network

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - PORT=${GREEN_PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "${GREEN_PORT}:${GREEN_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/healthz"]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    depends_on:
      - app_blue
      - app_green
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.tmpl:/etc/nginx/templates/default.conf.template:ro
      - ./entrypoint.sh:/docker-entrypoint.d/10-envsubst.sh:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    networks:
      - app-network

networks:
  app-network
    driver: bridge
